// AUTO-GENERATED by l0_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "gemm_performance_kernel.cpp"

using namespace pto;

void sw0() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 64, 16, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw1() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 128, 16, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw2() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 128, 16, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw3() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 256, 16, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw4() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 256, 16, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw5() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 256, 16, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw6() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 512, 16, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw7() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 512, 16, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw8() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 512, 16, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw9() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 64, 32, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw10() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 128, 32, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw11() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 128, 32, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw12() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 256, 32, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw13() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 256, 32, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw14() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 256, 32, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw15() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 512, 32, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw16() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 512, 32, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw17() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 512, 32, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw18() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 64, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw19() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 128, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw20() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw21() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 256, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw22() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 256, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw23() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 256, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw24() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 64, 128, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw25() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 128, 128, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw26() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 128, 128, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw27() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 32, 512, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw28() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 32, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw29() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 32, 512, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw30() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 32, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw31() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 32, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw32() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 256, 32, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw33() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 256, 32, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw34() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw35() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw36() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw37() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw38() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw39() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 256, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sw40() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 256, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }

TEST(GemmSweep, All) {
    LAUNCH_KERNEL(sw0, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw3, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw5, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw6, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw7, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw9, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw10, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw11, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw12, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw13, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw14, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw15, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw16, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw17, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw18, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw19, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw20, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw21, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw22, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw23, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw24, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw25, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw26, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw27, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw28, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw29, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw30, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw31, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw32, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw33, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw34, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw35, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw36, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw37, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw38, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw39, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sw40, , (1, nullptr, nullptr));
}
