// AUTO-GENERATED by gm_l1_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "gemm_performance_kernel.cpp"

using namespace pto;


template <pto::TileType LOC, typename T, int ROWS, int COLS, int N_LOADS>
AICORE inline void RunGmLoads(__gm__ T *src) {
    using ShapeDyn  = pto::Shape<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using StrideDyn = pto::Stride<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using Global    = pto::GlobalTensor<T, ShapeDyn, StrideDyn, pto::Layout::ND>;
    using TileT     = pto::Tile<LOC, T, ROWS, COLS, pto::BLayout::RowMajor, -1, -1>;
    TileT tile(ROWS, COLS);
    TASSIGN(tile, 0x0);
    constexpr int elems = ROWS * COLS;
    ShapeDyn  shape(1, 1, 1, ROWS, COLS);
    StrideDyn stride(elems, elems, elems, COLS, 1);
    for (int i = 0; i < N_LOADS; ++i) {
        Global g(src, shape, stride);
        TLOAD(tile, g);
    }
}

void ct_cube_un() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 0.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Mat, half, 128, 256, 64>(nullptr); }
void ct_vec_un() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 0.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Vec, half, 128, 256, 64>(nullptr); }
void ct_cube_1() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Mat, half, 128, 256, 64>(nullptr); }
void ct_vec_1() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Vec, half, 128, 256, 64>(nullptr); }
void ct_cube_2() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Mat, half, 128, 256, 64>(nullptr); }
void ct_vec_2() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Vec, half, 128, 256, 64>(nullptr); }
void ct_cube_4() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Mat, half, 128, 256, 64>(nullptr); }
void ct_vec_4() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Vec, half, 128, 256, 64>(nullptr); }
void ct_cube_8() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Mat, half, 128, 256, 64>(nullptr); }
void ct_vec_8() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Vec, half, 128, 256, 64>(nullptr); }
void ct_cube_16() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Mat, half, 128, 256, 64>(nullptr); }
void ct_vec_16() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Vec, half, 128, 256, 64>(nullptr); }
void ct_cube_24() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Mat, half, 128, 256, 64>(nullptr); }
void ct_vec_24() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGmLoads<pto::TileType::Vec, half, 128, 256, 64>(nullptr); }

TEST(Gml1Contention, All) {
    LAUNCH_KERNEL(ct_cube_un, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ct_vec_un, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ct_cube_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ct_vec_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ct_cube_2, , (2, nullptr, nullptr));
    LAUNCH_KERNEL(ct_vec_2, , (2, nullptr, nullptr));
    LAUNCH_KERNEL(ct_cube_4, , (4, nullptr, nullptr));
    LAUNCH_KERNEL(ct_vec_4, , (4, nullptr, nullptr));
    LAUNCH_KERNEL(ct_cube_8, , (8, nullptr, nullptr));
    LAUNCH_KERNEL(ct_vec_8, , (8, nullptr, nullptr));
    LAUNCH_KERNEL(ct_cube_16, , (16, nullptr, nullptr));
    LAUNCH_KERNEL(ct_vec_16, , (16, nullptr, nullptr));
    LAUNCH_KERNEL(ct_cube_24, , (24, nullptr, nullptr));
    LAUNCH_KERNEL(ct_vec_24, , (24, nullptr, nullptr));
}
