// AUTO-GENERATED by vec_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

using namespace pto;


template <int OP, typename T, int ROWS, int COLS, int NOPS>
AICORE inline void VecChain(__gm__ T *src) {
    using ShapeDyn  = pto::Shape<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using StrideDyn = pto::Stride<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using Global    = pto::GlobalTensor<T, ShapeDyn, StrideDyn, pto::Layout::ND>;
    using VT        = pto::Tile<pto::TileType::Vec, T, ROWS, COLS, pto::BLayout::RowMajor, ROWS, COLS>;
    constexpr int nbytes = ROWS * COLS * (int)sizeof(T);
    VT a, b, c;
    TASSIGN(a, 0);
    TASSIGN(b, nbytes);
    TASSIGN(c, 2 * nbytes);
    ShapeDyn  shape(1, 1, 1, ROWS, COLS);
    StrideDyn stride(ROWS * COLS, ROWS * COLS, ROWS * COLS, COLS, 1);
    Global g(src, shape, stride);
    TLOAD(a, g);
    TLOAD(b, g);
    for (int i = 0; i < NOPS; ++i) {
        if constexpr (OP == 0) { TADD(c, a, b); }
        else if constexpr (OP == 1) { TMUL(c, a, b); }
        else if constexpr (OP == 2) { TDIV(c, a, b); }
        else if constexpr (OP == 3) { TEXP(c, a); }
    }
}

void vp_add_r1() { VecChain<0, float, 1, 64, 1>(nullptr); }
void vp_add_r2() { VecChain<0, float, 1, 128, 1>(nullptr); }
void vp_add_r4() { VecChain<0, float, 1, 256, 1>(nullptr); }
void vp_add_r8() { VecChain<0, float, 1, 512, 1>(nullptr); }
void vp_add_r16() { VecChain<0, float, 1, 1024, 1>(nullptr); }
void vp_add_r32() { VecChain<0, float, 1, 2048, 1>(nullptr); }
void vp_add_r64() { VecChain<0, float, 1, 4096, 1>(nullptr); }
void vp_mul_r1() { VecChain<1, float, 1, 64, 1>(nullptr); }
void vp_mul_r2() { VecChain<1, float, 1, 128, 1>(nullptr); }
void vp_mul_r4() { VecChain<1, float, 1, 256, 1>(nullptr); }
void vp_mul_r8() { VecChain<1, float, 1, 512, 1>(nullptr); }
void vp_mul_r16() { VecChain<1, float, 1, 1024, 1>(nullptr); }
void vp_mul_r32() { VecChain<1, float, 1, 2048, 1>(nullptr); }
void vp_mul_r64() { VecChain<1, float, 1, 4096, 1>(nullptr); }
void vp_div_r1() { VecChain<2, float, 1, 64, 1>(nullptr); }
void vp_div_r2() { VecChain<2, float, 1, 128, 1>(nullptr); }
void vp_div_r4() { VecChain<2, float, 1, 256, 1>(nullptr); }
void vp_div_r8() { VecChain<2, float, 1, 512, 1>(nullptr); }
void vp_div_r16() { VecChain<2, float, 1, 1024, 1>(nullptr); }
void vp_div_r32() { VecChain<2, float, 1, 2048, 1>(nullptr); }
void vp_div_r64() { VecChain<2, float, 1, 4096, 1>(nullptr); }
void vp_exp_r1() { VecChain<3, float, 1, 64, 1>(nullptr); }
void vp_exp_r2() { VecChain<3, float, 1, 128, 1>(nullptr); }
void vp_exp_r4() { VecChain<3, float, 1, 256, 1>(nullptr); }
void vp_exp_r8() { VecChain<3, float, 1, 512, 1>(nullptr); }
void vp_exp_r16() { VecChain<3, float, 1, 1024, 1>(nullptr); }
void vp_exp_r32() { VecChain<3, float, 1, 2048, 1>(nullptr); }
void vp_exp_r64() { VecChain<3, float, 1, 4096, 1>(nullptr); }
void vp_chain_n1() { VecChain<0, float, 1, 512, 1>(nullptr); }
void vp_chain_n2() { VecChain<0, float, 1, 512, 2>(nullptr); }
void vp_chain_n4() { VecChain<0, float, 1, 512, 4>(nullptr); }
void vp_chain_n8() { VecChain<0, float, 1, 512, 8>(nullptr); }
void vp_chain_n16() { VecChain<0, float, 1, 512, 16>(nullptr); }

TEST(VecPointwise, All) {
    LAUNCH_KERNEL(vp_add_r1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_add_r2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_add_r4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_add_r8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_add_r16, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_add_r32, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_add_r64, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_mul_r1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_mul_r2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_mul_r4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_mul_r8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_mul_r16, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_mul_r32, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_mul_r64, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_div_r1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_div_r2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_div_r4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_div_r8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_div_r16, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_div_r32, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_div_r64, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_exp_r1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_exp_r2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_exp_r4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_exp_r8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_exp_r16, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_exp_r32, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_exp_r64, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_chain_n1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_chain_n2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_chain_n4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_chain_n8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vp_chain_n16, , (1, nullptr, nullptr));
}
