// AUTO-GENERATED by gm_l1_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "gemm_performance_kernel.cpp"

using namespace pto;

void rl0() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 16, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl1() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 16, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl2() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 16, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl3() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 16, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl4() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 16, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl5() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl6() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl7() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl8() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl9() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl10() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl11() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl12() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl13() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl14() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl15() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl16() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl17() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl18() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl19() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl20() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 256, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl21() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 256, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl22() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 256, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rl23() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 256, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }

TEST(Gml1Reload, All) {
    LAUNCH_KERNEL(rl0, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl3, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl5, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl6, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl7, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl9, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl10, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl11, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl12, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl13, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl14, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl15, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl16, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl17, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl18, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl19, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl20, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl21, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl22, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rl23, , (1, nullptr, nullptr));
}
