// AUTO-GENERATED by vec_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

using namespace pto;


template <typename T, int H, int WC>
AICORE inline void SplitReduce(__gm__ T *out) {
    using ShapeDyn  = pto::Shape<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using StrideDyn = pto::Stride<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using Global    = pto::GlobalTensor<T, ShapeDyn, StrideDyn, pto::Layout::ND>;
    using VT = pto::Tile<pto::TileType::Vec, T, H, WC, pto::BLayout::RowMajor, H, WC>;
    using RT = pto::Tile<pto::TileType::Vec, T, H, 1, pto::BLayout::ColMajor, H, 1>;
    constexpr int nb = H * WC * (int)sizeof(T);
    VT src, tmp; RT partial;
    TASSIGN(src, 0);
    TASSIGN(tmp, nb);
    TASSIGN(partial, 2 * nb);
    TROWSUM(partial, src, tmp);                  // per-core band reduce [H,WC] -> [H,1]
    ShapeDyn  shape(1, 1, 1, H, 1);
    StrideDyn stride(H, H, H, 1, 1);
    Global g(out, shape, stride);
    TSTORE(g, partial);                          // write the thin [H,1] partial (UB->GM / mte3)
}

void sp_s1() { SplitReduce<float, 8, 512>(nullptr); }
void sp_s2() { SplitReduce<float, 8, 256>(nullptr); }
void sp_s4() { SplitReduce<float, 8, 128>(nullptr); }
void sp_s8() { SplitReduce<float, 8, 64>(nullptr); }

TEST(VecSplitS, All) {
    LAUNCH_KERNEL(sp_s1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sp_s2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sp_s4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sp_s8, , (1, nullptr, nullptr));
}
