// AUTO-GENERATED by gm_l1_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "chain_fused_kernel.cpp"

using namespace pto;

void fz_128_256_128_256() { gm_l1_chain::RunGemmChainFused<float, half, half, 128, 256, 128, 256, 128, 64, 64>(nullptr, nullptr, nullptr, nullptr); }
void fz_128_256_128_256_mm1() { RunGemmE2E<float, half, half, float, 1, 128, 256, 128, 128, 256, 128, 128, 256, 128, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fz_128_256_128_256_mm2() { RunGemmE2E<float, half, half, float, 1, 128, 128, 256, 128, 128, 256, 128, 128, 256, 128, 128, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fz_128_512_128_512() { gm_l1_chain::RunGemmChainFused<float, half, half, 128, 512, 128, 512, 128, 64, 64>(nullptr, nullptr, nullptr, nullptr); }
void fz_128_512_128_512_mm1() { RunGemmE2E<float, half, half, float, 1, 128, 512, 128, 128, 512, 128, 128, 512, 128, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fz_128_512_128_512_mm2() { RunGemmE2E<float, half, half, float, 1, 128, 128, 512, 128, 128, 512, 128, 128, 512, 128, 128, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fz_128_512_256_512() { gm_l1_chain::RunGemmChainFused<float, half, half, 128, 512, 256, 512, 128, 64, 64>(nullptr, nullptr, nullptr, nullptr); }
void fz_128_512_256_512_mm1() { RunGemmE2E<float, half, half, float, 1, 128, 512, 256, 128, 512, 256, 128, 512, 256, 128, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fz_128_512_256_512_mm2() { RunGemmE2E<float, half, half, float, 1, 128, 256, 512, 128, 256, 512, 128, 256, 512, 128, 256, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }

TEST(Gml1Fused, All) {
    LAUNCH_KERNEL(fz_128_256_128_256, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fz_128_256_128_256_mm1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fz_128_256_128_256_mm2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fz_128_512_128_512, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fz_128_512_128_512_mm1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fz_128_512_128_512_mm2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fz_128_512_256_512, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fz_128_512_256_512_mm1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fz_128_512_256_512_mm2, , (1, nullptr, nullptr));
}
