// AUTO-GENERATED by gm_l1_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "gemm_performance_kernel.cpp"

using namespace pto;

void rf_skinny_membound() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rf_smalltile_reload() { RunGemmE2E<float, half, half, float, 1, 512, 256, 512, 512, 256, 512, 512, 256, 512, 64, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rf_balanced() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rf_deepk_compute() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void rf_square_compute() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }

TEST(Gml1Roofline, All) {
    LAUNCH_KERNEL(rf_skinny_membound, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rf_smalltile_reload, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rf_balanced, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rf_deepk_compute, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rf_square_compute, , (1, nullptr, nullptr));
}
