// AUTO-GENERATED by mixed_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>
#include "gemm_performance_kernel.cpp"

using namespace pto;


// One [BM,N] output tile = A_block @ B  (fp16 in, fp32 acc), via the proven gemm kernel.
// baseK = BK (= min(K,128)) keeps the L0A/L0B ping-pong <= 32 KiB; singleCoreK = K, so the cube
// runs a kLoop = K/BK accumulate loop for K > 128. BK defaults to min(K,128) at the call sites.
template <int BM, int K, int N, int BK>
AICORE inline void CubeTile(__gm__ float *out, __gm__ half *a, __gm__ half *b) {
    RunGemmE2E<float, half, half, float, /*blockDim=*/1,
               BM, K, N, BM, K, N, BM, K, N, BM, BK, N, 1, 1, 1, 1>(out, a, b);
}

// In-place pointwise epilogue over the [BM,N] handoff tile: load GM->UB, op, store UB->GM. The
// TLOAD reads `cbuf` -> a cross-pipe RAW edge onto the cube FIX store that produced it; the
// TSTORE re-registers `cbuf` as freshly written (read by the next cube in the serial chain).
template <int OP, int BM, int N>
AICORE inline void VectorTile(__gm__ float *cbuf, std::size_t ub_off) {
    using ShapeDyn  = pto::Shape<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using StrideDyn = pto::Stride<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using Global    = pto::GlobalTensor<float, ShapeDyn, StrideDyn, pto::Layout::ND>;
    using VT        = pto::Tile<pto::TileType::Vec, float, BM, N, pto::BLayout::RowMajor, BM, N>;
    VT v;
    TASSIGN(v, ub_off);
    ShapeDyn  shape(1, 1, 1, BM, N);
    StrideDyn stride(BM * N, BM * N, BM * N, N, 1);
    Global g(cbuf, shape, stride);
    TLOAD(v, g);                                  // GM->UB (MTE2_AIV): waits the cube store on cbuf
    if constexpr (OP == 0) { TADD(v, v, v); }     // VEC: C = C + C
    else if constexpr (OP == 3) { TEXP(v, v); }   // VEC: C = exp(C)
    TSTORE(g, v);                                 // UB->GM (MTE3): re-registers cbuf's writer
}

// SKEWED ping-pong: the cube produces tile 0 up front, then each loop step produces tile k+1 into
// the OTHER of two GM buffers while the vector consumes tile k from THIS buffer. cube(k+1) and
// vector(k) touch different buffers -> no dep -> the two units overlap. The per-tile RAW (vector
// reads the cube's buffer) is hidden one tile deep. NTILES=1 degenerates to a single serial tile.
template <int OP, int BM, int K, int N, int NTILES, int BK = (K < 128 ? K : 128)>
AICORE inline void MixedOverlap(__gm__ half *A, __gm__ half *B, __gm__ float *buf0, __gm__ float *buf1) {
    __gm__ float *buf[2] = {buf0, buf1};
    CubeTile<BM, K, N, BK>(buf[0], A, B);                                  // prologue: produce tile 0
    for (int k = 0; k < NTILES; ++k) {
        if (k + 1 < NTILES) {
            CubeTile<BM, K, N, BK>(buf[(k + 1) & 1], A + (k + 1) * BM * K, B);  // produce tile k+1 (other buffer)
        }
        VectorTile<OP, BM, N>(buf[k & 1], 0x100000);                       // consume tile k (this buffer)
    }
}

// SERIAL: one handoff buffer H, reused every tile. cube(k>=1) takes its B operand FROM H (the
// buffer the prior vector wrote) -> a tracked RAW edge -> cube(k) cannot start until vector(k-1)
// finishes. vector(k) then waits cube(k) (RAW on H). The chain cube(0)->vec(0)->cube(1)->...
// is fully serialized: total ~= NTILES*(cube + vec).
template <int OP, int BM, int K, int N, int NTILES, int BK = (K < 128 ? K : 128)>
AICORE inline void MixedSerial(__gm__ half *A, __gm__ half *B, __gm__ float *H) {
    for (int k = 0; k < NTILES; ++k) {
        __gm__ half *bk = (k == 0) ? B : reinterpret_cast<__gm__ half *>(H);  // chain B<-H for k>=1
        CubeTile<BM, K, N, BK>(H, A + k * BM * K, bk);   // k>=1: the B-load on H waits vector(k-1)
        VectorTile<OP, BM, N>(H, 0x100000);              // reads H -> waits cube(k)
    }
}


// vec1 PRE-op: A' = A + A over [BM,K] (half), read `src` -> write `dst`. An AIV (vector) op that
// feeds the cube's left operand; the cube then reads A' (RAW on this store) one stage downstream.
template <int OP, int BM, int K>
AICORE inline void VecPreOp(__gm__ half *src, __gm__ half *dst, std::size_t ub_off) {
    using ShapeDyn  = pto::Shape<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using StrideDyn = pto::Stride<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using Global    = pto::GlobalTensor<half, ShapeDyn, StrideDyn, pto::Layout::ND>;
    using VT        = pto::Tile<pto::TileType::Vec, half, BM, K, pto::BLayout::RowMajor, BM, K>;
    VT v;
    TASSIGN(v, ub_off);
    ShapeDyn  shape(1, 1, 1, BM, K);
    StrideDyn stride(BM * K, BM * K, BM * K, K, 1);
    Global gs(src, shape, stride);
    Global gd(dst, shape, stride);
    TLOAD(v, gs);                                 // read A  (GM->UB, MTE2_AIV)
    if constexpr (OP == 0) { TADD(v, v, v); }     // A' = A + A  (VEC)
    else if constexpr (OP == 3) { TEXP(v, v); }
    TSTORE(gd, v);                                // write A' (UB->GM, MTE3): cube reads this next
}

// SKEWED 3-stage: vec1(k) -> cube(k) -> vec2(k). vec1 and vec2 BOTH run on the AIV; the cube on the
// AIC. Both handoffs (A'-buf, C-buf) are ping-ponged, and the pipeline is skewed two deep so
// vec1[k+2] || cube[k+1] || vec2[k] overlap. vec2(k) can first start only after vec1(0)->cube(0)
// have BOTH landed, so the prologue fill deepens to vec1_tile + cube_tile (vs the 2-stage cube_tile).
template <int OP, int BM, int K, int N, int NTILES, int BK = (K < 128 ? K : 128)>
AICORE inline void MixedVCV(__gm__ half *A, __gm__ half *B, __gm__ half *ap0, __gm__ half *ap1,
                            __gm__ float *c0, __gm__ float *c1) {
    __gm__ half  *ap[2] = {ap0, ap1};
    __gm__ float *cb[2] = {c0, c1};
    VecPreOp<OP, BM, K>(A, ap[0], 0x200000);                              // vec1(0) -> ap[0]
    CubeTile<BM, K, N, BK>(cb[0], ap[0], B);                             // cube(0): ap[0] -> cb[0]
    if (NTILES > 1) VecPreOp<OP, BM, K>(A + BM * K, ap[1], 0x200000);     // vec1(1) -> ap[1]
    for (int k = 0; k < NTILES; ++k) {
        VectorTile<OP, BM, N>(cb[k & 1], 0x100000);                          // vec2(k): consume C[k]
        if (k + 1 < NTILES)
            CubeTile<BM, K, N, BK>(cb[(k + 1) & 1], ap[(k + 1) & 1], B);     // cube(k+1)
        if (k + 2 < NTILES)
            VecPreOp<OP, BM, K>(A + (k + 2) * BM * K, ap[(k + 2) & 1], 0x200000);  // vec1(k+2)
    }
}

void vcv_bm128_n128_k128_t1() {
    static __gm__ half  *const A   = reinterpret_cast<__gm__ half  *>(0x10000000);
    static __gm__ half  *const B   = reinterpret_cast<__gm__ half  *>(0x20000000);
    static __gm__ half  *const ap0 = reinterpret_cast<__gm__ half  *>(0x50000000);
    static __gm__ half  *const ap1 = reinterpret_cast<__gm__ half  *>(0x54000000);
    static __gm__ float *const c0  = reinterpret_cast<__gm__ float *>(0x60000000);
    static __gm__ float *const c1  = reinterpret_cast<__gm__ float *>(0x64000000);
    MixedVCV<0, 128, 128, 128, 1>(A, B, ap0, ap1, c0, c1);
}
void vcv_bm128_n128_k128_t2() {
    static __gm__ half  *const A   = reinterpret_cast<__gm__ half  *>(0x10000000);
    static __gm__ half  *const B   = reinterpret_cast<__gm__ half  *>(0x20000000);
    static __gm__ half  *const ap0 = reinterpret_cast<__gm__ half  *>(0x50000000);
    static __gm__ half  *const ap1 = reinterpret_cast<__gm__ half  *>(0x54000000);
    static __gm__ float *const c0  = reinterpret_cast<__gm__ float *>(0x60000000);
    static __gm__ float *const c1  = reinterpret_cast<__gm__ float *>(0x64000000);
    MixedVCV<0, 128, 128, 128, 2>(A, B, ap0, ap1, c0, c1);
}
void vcv_bm128_n128_k128_t4() {
    static __gm__ half  *const A   = reinterpret_cast<__gm__ half  *>(0x10000000);
    static __gm__ half  *const B   = reinterpret_cast<__gm__ half  *>(0x20000000);
    static __gm__ half  *const ap0 = reinterpret_cast<__gm__ half  *>(0x50000000);
    static __gm__ half  *const ap1 = reinterpret_cast<__gm__ half  *>(0x54000000);
    static __gm__ float *const c0  = reinterpret_cast<__gm__ float *>(0x60000000);
    static __gm__ float *const c1  = reinterpret_cast<__gm__ float *>(0x64000000);
    MixedVCV<0, 128, 128, 128, 4>(A, B, ap0, ap1, c0, c1);
}
void vcv_bm128_n128_k128_t8() {
    static __gm__ half  *const A   = reinterpret_cast<__gm__ half  *>(0x10000000);
    static __gm__ half  *const B   = reinterpret_cast<__gm__ half  *>(0x20000000);
    static __gm__ half  *const ap0 = reinterpret_cast<__gm__ half  *>(0x50000000);
    static __gm__ half  *const ap1 = reinterpret_cast<__gm__ half  *>(0x54000000);
    static __gm__ float *const c0  = reinterpret_cast<__gm__ float *>(0x60000000);
    static __gm__ float *const c1  = reinterpret_cast<__gm__ float *>(0x64000000);
    MixedVCV<0, 128, 128, 128, 8>(A, B, ap0, ap1, c0, c1);
}

TEST(MixedVcv, All) {
    LAUNCH_KERNEL(vcv_bm128_n128_k128_t1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vcv_bm128_n128_k128_t2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vcv_bm128_n128_k128_t4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(vcv_bm128_n128_k128_t8, , (1, nullptr, nullptr));
}
