// AUTO-GENERATED by mixed_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>
#include "gemm_performance_kernel.cpp"

using namespace pto;


// One [BM,N] output tile = A_block @ B  (fp16 in, fp32 acc), via the proven gemm kernel.
// baseK = BK (= min(K,128)) keeps the L0A/L0B ping-pong <= 32 KiB; singleCoreK = K, so the cube
// runs a kLoop = K/BK accumulate loop for K > 128. BK defaults to min(K,128) at the call sites.
template <int BM, int K, int N, int BK>
AICORE inline void CubeTile(__gm__ float *out, __gm__ half *a, __gm__ half *b) {
    RunGemmE2E<float, half, half, float, /*blockDim=*/1,
               BM, K, N, BM, K, N, BM, K, N, BM, BK, N, 1, 1, 1, 1>(out, a, b);
}

// In-place pointwise epilogue over the [BM,N] handoff tile: load GM->UB, op, store UB->GM. The
// TLOAD reads `cbuf` -> a cross-pipe RAW edge onto the cube FIX store that produced it; the
// TSTORE re-registers `cbuf` as freshly written (read by the next cube in the serial chain).
template <int OP, int BM, int N>
AICORE inline void VectorTile(__gm__ float *cbuf, std::size_t ub_off) {
    using ShapeDyn  = pto::Shape<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using StrideDyn = pto::Stride<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using Global    = pto::GlobalTensor<float, ShapeDyn, StrideDyn, pto::Layout::ND>;
    using VT        = pto::Tile<pto::TileType::Vec, float, BM, N, pto::BLayout::RowMajor, BM, N>;
    VT v;
    TASSIGN(v, ub_off);
    ShapeDyn  shape(1, 1, 1, BM, N);
    StrideDyn stride(BM * N, BM * N, BM * N, N, 1);
    Global g(cbuf, shape, stride);
    TLOAD(v, g);                                  // GM->UB (MTE2_AIV): waits the cube store on cbuf
    if constexpr (OP == 0) { TADD(v, v, v); }     // VEC: C = C + C
    else if constexpr (OP == 3) { TEXP(v, v); }   // VEC: C = exp(C)
    TSTORE(g, v);                                 // UB->GM (MTE3): re-registers cbuf's writer
}

// SKEWED ping-pong: the cube produces tile 0 up front, then each loop step produces tile k+1 into
// the OTHER of two GM buffers while the vector consumes tile k from THIS buffer. cube(k+1) and
// vector(k) touch different buffers -> no dep -> the two units overlap. The per-tile RAW (vector
// reads the cube's buffer) is hidden one tile deep. NTILES=1 degenerates to a single serial tile.
template <int OP, int BM, int K, int N, int NTILES, int BK = (K < 128 ? K : 128)>
AICORE inline void MixedOverlap(__gm__ half *A, __gm__ half *B, __gm__ float *buf0, __gm__ float *buf1) {
    __gm__ float *buf[2] = {buf0, buf1};
    CubeTile<BM, K, N, BK>(buf[0], A, B);                                  // prologue: produce tile 0
    for (int k = 0; k < NTILES; ++k) {
        if (k + 1 < NTILES) {
            CubeTile<BM, K, N, BK>(buf[(k + 1) & 1], A + (k + 1) * BM * K, B);  // produce tile k+1 (other buffer)
        }
        VectorTile<OP, BM, N>(buf[k & 1], 0x100000);                       // consume tile k (this buffer)
    }
}

// SERIAL: one handoff buffer H, reused every tile. cube(k>=1) takes its B operand FROM H (the
// buffer the prior vector wrote) -> a tracked RAW edge -> cube(k) cannot start until vector(k-1)
// finishes. vector(k) then waits cube(k) (RAW on H). The chain cube(0)->vec(0)->cube(1)->...
// is fully serialized: total ~= NTILES*(cube + vec).
template <int OP, int BM, int K, int N, int NTILES, int BK = (K < 128 ? K : 128)>
AICORE inline void MixedSerial(__gm__ half *A, __gm__ half *B, __gm__ float *H) {
    for (int k = 0; k < NTILES; ++k) {
        __gm__ half *bk = (k == 0) ? B : reinterpret_cast<__gm__ half *>(H);  // chain B<-H for k>=1
        CubeTile<BM, K, N, BK>(H, A + k * BM * K, bk);   // k>=1: the B-load on H waits vector(k-1)
        VectorTile<OP, BM, N>(H, 0x100000);              // reads H -> waits cube(k)
    }
}

void ms_bm128_n128_k128_t1() {
    static __gm__ half  *const A = reinterpret_cast<__gm__ half  *>(0x10000000);
    static __gm__ half  *const B = reinterpret_cast<__gm__ half  *>(0x20000000);
    static __gm__ float *const H = reinterpret_cast<__gm__ float *>(0x30000000);
    MixedSerial<0, 128, 128, 128, 1>(A, B, H);
}
void ms_bm128_n128_k128_t2() {
    static __gm__ half  *const A = reinterpret_cast<__gm__ half  *>(0x10000000);
    static __gm__ half  *const B = reinterpret_cast<__gm__ half  *>(0x20000000);
    static __gm__ float *const H = reinterpret_cast<__gm__ float *>(0x30000000);
    MixedSerial<0, 128, 128, 128, 2>(A, B, H);
}
void ms_bm128_n128_k128_t4() {
    static __gm__ half  *const A = reinterpret_cast<__gm__ half  *>(0x10000000);
    static __gm__ half  *const B = reinterpret_cast<__gm__ half  *>(0x20000000);
    static __gm__ float *const H = reinterpret_cast<__gm__ float *>(0x30000000);
    MixedSerial<0, 128, 128, 128, 4>(A, B, H);
}
void ms_bm128_n128_k128_t8() {
    static __gm__ half  *const A = reinterpret_cast<__gm__ half  *>(0x10000000);
    static __gm__ half  *const B = reinterpret_cast<__gm__ half  *>(0x20000000);
    static __gm__ float *const H = reinterpret_cast<__gm__ float *>(0x30000000);
    MixedSerial<0, 128, 128, 128, 8>(A, B, H);
}
void ms_bm64_n128_k128_t1() {
    static __gm__ half  *const A = reinterpret_cast<__gm__ half  *>(0x10000000);
    static __gm__ half  *const B = reinterpret_cast<__gm__ half  *>(0x20000000);
    static __gm__ float *const H = reinterpret_cast<__gm__ float *>(0x30000000);
    MixedSerial<0, 64, 128, 128, 1>(A, B, H);
}
void ms_bm64_n128_k128_t2() {
    static __gm__ half  *const A = reinterpret_cast<__gm__ half  *>(0x10000000);
    static __gm__ half  *const B = reinterpret_cast<__gm__ half  *>(0x20000000);
    static __gm__ float *const H = reinterpret_cast<__gm__ float *>(0x30000000);
    MixedSerial<0, 64, 128, 128, 2>(A, B, H);
}
void ms_bm64_n128_k128_t4() {
    static __gm__ half  *const A = reinterpret_cast<__gm__ half  *>(0x10000000);
    static __gm__ half  *const B = reinterpret_cast<__gm__ half  *>(0x20000000);
    static __gm__ float *const H = reinterpret_cast<__gm__ float *>(0x30000000);
    MixedSerial<0, 64, 128, 128, 4>(A, B, H);
}
void ms_bm64_n128_k128_t8() {
    static __gm__ half  *const A = reinterpret_cast<__gm__ half  *>(0x10000000);
    static __gm__ half  *const B = reinterpret_cast<__gm__ half  *>(0x20000000);
    static __gm__ float *const H = reinterpret_cast<__gm__ float *>(0x30000000);
    MixedSerial<0, 64, 128, 128, 8>(A, B, H);
}

TEST(MixedSerial, All) {
    LAUNCH_KERNEL(ms_bm128_n128_k128_t1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ms_bm128_n128_k128_t2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ms_bm128_n128_k128_t4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ms_bm128_n128_k128_t8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ms_bm64_n128_k128_t1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ms_bm64_n128_k128_t2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ms_bm64_n128_k128_t4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ms_bm64_n128_k128_t8, , (1, nullptr, nullptr));
}
