// AUTO-GENERATED by vec_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

using namespace pto;


// Mirror the ST trowsum/tcolsum tests: full [ROWS,COLS] template (aligned Cols) with
// DYNAMIC valid dims (-1,-1) + runtime ctor giving each tile its real valid shape. No
// TLOAD -- the cost model is data-agnostic, so TASSIGN + the reduce op is enough.
template <typename T, int ROWS, int COLS>
AICORE inline void RowSum() {
    using TD = pto::Tile<pto::TileType::Vec, T, ROWS, COLS, pto::BLayout::RowMajor, -1, -1>;
    constexpr int nbytes = ROWS * COLS * (int)sizeof(T);
    TD src(ROWS, COLS), tmp(ROWS, COLS), dst(ROWS, COLS);
    TASSIGN(src, 0);
    TASSIGN(tmp, nbytes);
    TASSIGN(dst, 2 * nbytes);
    TROWSUM(dst, src, tmp);          // [ROWS,COLS] -> [ROWS,1] (reduce W)
}
template <typename T, int ROWS, int COLS>
AICORE inline void ColSumBin() {
    using TD = pto::Tile<pto::TileType::Vec, T, ROWS, COLS, pto::BLayout::RowMajor, -1, -1>;
    constexpr int nbytes = ROWS * COLS * (int)sizeof(T);
    TD src(ROWS, COLS), tmp((ROWS / 2 > 0 ? ROWS / 2 : 1), COLS), dst(1, COLS);
    TASSIGN(src, 0);
    TASSIGN(tmp, nbytes);
    TASSIGN(dst, 2 * nbytes);
    TCOLSUM(dst, src, tmp, true);    // [ROWS,COLS] -> [1,COLS] (reduce H, binary tree)
}

void rs_c64() { RowSum<float, 8, 64>(); }
void rs_c128() { RowSum<float, 8, 128>(); }
void rs_c256() { RowSum<float, 8, 256>(); }
void rs_c512() { RowSum<float, 8, 512>(); }
void rs_c1024() { RowSum<float, 8, 1024>(); }
void rs_r8() { RowSum<float, 8, 128>(); }
void rs_r16() { RowSum<float, 16, 128>(); }
void rs_r32() { RowSum<float, 32, 128>(); }
void rs_r64() { RowSum<float, 64, 128>(); }
void cs_r2() { ColSumBin<float, 2, 128>(); }
void cs_r4() { ColSumBin<float, 4, 128>(); }
void cs_r8() { ColSumBin<float, 8, 128>(); }
void cs_r16() { ColSumBin<float, 16, 128>(); }
void cs_r32() { ColSumBin<float, 32, 128>(); }
void cs_r64() { ColSumBin<float, 64, 128>(); }

TEST(VecReduce, All) {
    LAUNCH_KERNEL(rs_c64, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rs_c128, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rs_c256, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rs_c512, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rs_c1024, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rs_r8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rs_r16, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rs_r32, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rs_r64, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(cs_r2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(cs_r4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(cs_r8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(cs_r16, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(cs_r32, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(cs_r64, , (1, nullptr, nullptr));
}
