// AUTO-GENERATED by gm_l1_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "gemm_performance_kernel.cpp"

using namespace pto;

void sk1() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sk2() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 128, 1, 2, 2, 1>(nullptr, nullptr, nullptr); }
void sk4() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 128, 1, 4, 4, 1>(nullptr, nullptr, nullptr); }

TEST(Gml1StepK, All) {
    LAUNCH_KERNEL(sk1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sk2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sk4, , (1, nullptr, nullptr));
}
