// AUTO-GENERATED by gm_l1_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "gemm_performance_kernel.cpp"

using namespace pto;

void ch128_mm1() { RunGemmE2E<float, half, half, float, 1, 512, 512, 128, 512, 512, 128, 512, 512, 128, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void ch128_mm2() { RunGemmE2E<float, half, half, float, 1, 512, 128, 512, 512, 128, 512, 512, 128, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void ch256_mm1() { RunGemmE2E<float, half, half, float, 1, 512, 512, 256, 512, 512, 256, 512, 512, 256, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void ch256_mm2() { RunGemmE2E<float, half, half, float, 1, 512, 256, 512, 512, 256, 512, 512, 256, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void ch512_mm1() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void ch512_mm2() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }

TEST(Gml1Chain, All) {
    LAUNCH_KERNEL(ch128_mm1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ch128_mm2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ch256_mm1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ch256_mm2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ch512_mm1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ch512_mm2, , (1, nullptr, nullptr));
}
