// AUTO-GENERATED by l0_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "dbc_kernel.cpp"

using namespace pto;

void dbc_big1_0() { RunGemmSplitKDBC<float, half, half, 512, 64, 512, 256, 64, 128, 1>(nullptr, nullptr, nullptr); }
void dbc_small1_0() { RunGemmSplitKDBC<float, half, half, 512, 64, 512, 128, 64, 128, 1>(nullptr, nullptr, nullptr); }
void dbc_small2_0() { RunGemmSplitKDBC<float, half, half, 512, 64, 512, 128, 64, 128, 2>(nullptr, nullptr, nullptr); }
void dbc_big1_1() { RunGemmSplitKDBC<float, half, half, 512, 128, 512, 256, 64, 128, 1>(nullptr, nullptr, nullptr); }
void dbc_small1_1() { RunGemmSplitKDBC<float, half, half, 512, 128, 512, 128, 64, 128, 1>(nullptr, nullptr, nullptr); }
void dbc_small2_1() { RunGemmSplitKDBC<float, half, half, 512, 128, 512, 128, 64, 128, 2>(nullptr, nullptr, nullptr); }
void dbc_big1_2() { RunGemmSplitKDBC<float, half, half, 512, 256, 512, 256, 64, 128, 1>(nullptr, nullptr, nullptr); }
void dbc_small1_2() { RunGemmSplitKDBC<float, half, half, 512, 256, 512, 128, 64, 128, 1>(nullptr, nullptr, nullptr); }
void dbc_small2_2() { RunGemmSplitKDBC<float, half, half, 512, 256, 512, 128, 64, 128, 2>(nullptr, nullptr, nullptr); }

TEST(GemmDBC, All) {
    LAUNCH_KERNEL(dbc_big1_0, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dbc_small1_0, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dbc_small2_0, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dbc_big1_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dbc_small1_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dbc_small2_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dbc_big1_2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dbc_small1_2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dbc_small2_2, , (1, nullptr, nullptr));
}
