// AUTO-GENERATED by l0_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "accblock_kernel.cpp"

using namespace pto;

void ab_0_1() { RunGemmAccBlock<float, half, half, 512, 128, 512, 128, 64, 64, 1>(nullptr, nullptr, nullptr); }
void ab_0_2() { RunGemmAccBlock<float, half, half, 512, 128, 512, 128, 64, 64, 2>(nullptr, nullptr, nullptr); }
void ab_0_4() { RunGemmAccBlock<float, half, half, 512, 128, 512, 128, 64, 64, 4>(nullptr, nullptr, nullptr); }
void ab_1_1() { RunGemmAccBlock<float, half, half, 512, 256, 512, 128, 64, 64, 1>(nullptr, nullptr, nullptr); }
void ab_1_2() { RunGemmAccBlock<float, half, half, 512, 256, 512, 128, 64, 64, 2>(nullptr, nullptr, nullptr); }
void ab_1_4() { RunGemmAccBlock<float, half, half, 512, 256, 512, 128, 64, 64, 4>(nullptr, nullptr, nullptr); }
void ab_2_1() { RunGemmAccBlock<float, half, half, 512, 128, 512, 128, 64, 128, 1>(nullptr, nullptr, nullptr); }
void ab_2_2() { RunGemmAccBlock<float, half, half, 512, 128, 512, 128, 64, 128, 2>(nullptr, nullptr, nullptr); }

TEST(GemmAccBlock, All) {
    LAUNCH_KERNEL(ab_0_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ab_0_2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ab_0_4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ab_1_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ab_1_2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ab_1_4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ab_2_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(ab_2_2, , (1, nullptr, nullptr));
}
