// AUTO-GENERATED by l0_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "fullk_reuse_kernel.cpp"

using namespace pto;

void fk_base_0() { RunGemmE2E<float, half, half, float, 1, 512, 64, 512, 512, 64, 512, 512, 64, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fk_astat_0() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 128, 128, true>(nullptr, nullptr, nullptr); }
void fk_bstat_0() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 128, 128, false>(nullptr, nullptr, nullptr); }
void fk_base_1() { RunGemmE2E<float, half, half, float, 1, 512, 64, 512, 512, 64, 512, 512, 64, 512, 256, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fk_astat_1() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 256, 128, true>(nullptr, nullptr, nullptr); }
void fk_bstat_1() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 256, 128, false>(nullptr, nullptr, nullptr); }
void fk_base_2() { RunGemmE2E<float, half, half, float, 1, 512, 64, 512, 512, 64, 512, 512, 64, 512, 128, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fk_astat_2() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 128, 256, true>(nullptr, nullptr, nullptr); }
void fk_bstat_2() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 128, 256, false>(nullptr, nullptr, nullptr); }
void fk_base_3() { RunGemmE2E<float, half, half, float, 1, 512, 64, 512, 512, 64, 512, 512, 64, 512, 256, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fk_astat_3() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 256, 64, true>(nullptr, nullptr, nullptr); }
void fk_bstat_3() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 256, 64, false>(nullptr, nullptr, nullptr); }
void fk_base_4() { RunGemmE2E<float, half, half, float, 1, 512, 64, 512, 512, 64, 512, 512, 64, 512, 64, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fk_astat_4() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 64, 256, true>(nullptr, nullptr, nullptr); }
void fk_bstat_4() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 64, 256, false>(nullptr, nullptr, nullptr); }
void fk_base_5() { RunGemmE2E<float, half, half, float, 1, 512, 64, 512, 512, 64, 512, 512, 64, 512, 128, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fk_astat_5() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 128, 64, true>(nullptr, nullptr, nullptr); }
void fk_bstat_5() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 128, 64, false>(nullptr, nullptr, nullptr); }
void fk_base_6() { RunGemmE2E<float, half, half, float, 1, 512, 64, 512, 512, 64, 512, 512, 64, 512, 64, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fk_astat_6() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 64, 128, true>(nullptr, nullptr, nullptr); }
void fk_bstat_6() { RunGemmFullKReuse<float, half, half, 512, 64, 512, 64, 128, false>(nullptr, nullptr, nullptr); }
void fk_base_7() { RunGemmE2E<float, half, half, float, 1, 512, 128, 512, 512, 128, 512, 512, 128, 512, 128, 128, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fk_astat_7() { RunGemmFullKReuse<float, half, half, 512, 128, 512, 128, 128, true>(nullptr, nullptr, nullptr); }
void fk_bstat_7() { RunGemmFullKReuse<float, half, half, 512, 128, 512, 128, 128, false>(nullptr, nullptr, nullptr); }
void fk_base_8() { RunGemmE2E<float, half, half, float, 1, 512, 128, 512, 512, 128, 512, 512, 128, 512, 128, 128, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fk_astat_8() { RunGemmFullKReuse<float, half, half, 512, 128, 512, 128, 64, true>(nullptr, nullptr, nullptr); }
void fk_bstat_8() { RunGemmFullKReuse<float, half, half, 512, 128, 512, 128, 64, false>(nullptr, nullptr, nullptr); }
void fk_base_9() { RunGemmE2E<float, half, half, float, 1, 512, 128, 512, 512, 128, 512, 512, 128, 512, 64, 128, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void fk_astat_9() { RunGemmFullKReuse<float, half, half, 512, 128, 512, 64, 128, true>(nullptr, nullptr, nullptr); }
void fk_bstat_9() { RunGemmFullKReuse<float, half, half, 512, 128, 512, 64, 128, false>(nullptr, nullptr, nullptr); }

TEST(GemmFullK, All) {
    LAUNCH_KERNEL(fk_base_0, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_astat_0, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_bstat_0, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_base_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_astat_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_bstat_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_base_2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_astat_2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_bstat_2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_base_3, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_astat_3, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_bstat_3, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_base_4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_astat_4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_bstat_4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_base_5, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_astat_5, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_bstat_5, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_base_6, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_astat_6, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_bstat_6, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_base_7, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_astat_7, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_bstat_7, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_base_8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_astat_8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_bstat_8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_base_9, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_astat_9, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fk_bstat_9, , (1, nullptr, nullptr));
}
