# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# Shared constants, the analytic a2a3 cost model, and a perf-sim CSV reader for the
# L0-tile cost-model study. See README.md for the full write-up.

import csv
import pathlib

# --- paths (this study is self-contained; results land under results/) ---
STUDY_DIR = pathlib.Path(__file__).resolve().parent
PERF_SIM_ROOT = STUDY_DIR.parent                      # tests/costmodel/perf_sim_st
TESTCASE_DIR = PERF_SIM_ROOT / "testcase"
KERNEL_INCLUDE = "../../../kernels/manual/a2a3/gemm_performance"  # for CMake include dir
RESULTS_DIR = STUDY_DIR / "results"
CSV_DIR = RESULTS_DIR / "perf_sim_output"             # where LAUNCH_KERNEL writes summaries

# --- a2a3 cost-model constants (pto-isa include/pto/costmodel/arch_config.hpp) ---
FREQ_HZ = 1.85e9
BW_L1_L0A = 441.0     # GB/s  (L1 -> L0A, the cube's "left"/A port)
BW_L1_L0B = 220.5     # GB/s  (L1 -> L0B, the "right"/B port; exactly half of A)
BW_L0C_L1 = 128.0     # GB/s  (FIXPIPE drain to L1 / Mat scratch)
BW_L0C_GM = 70.0      # GB/s  (FIXPIPE drain to GM)

# --- buffer capacities (bytes) ---
L0A = L0B = 64 * 1024
L0C = 128 * 1024
L0_PING = 32 * 1024   # per ping-pong slot when an operand buffer is double-buffered

BYTES = {"bf16": 2, "fp32": 4}


def ceil_div(a, b):
    return (a + b - 1) // b


def divisors(d, align=16, lo=16):
    return [x for x in range(lo, d + 1, align) if d % x == 0]


def mad_cycles(m, k, n, bytes_a=2):
    """Cube MAD cost (pto-isa formula_backend_compute.hpp): one TMATMUL call."""
    kt = 32 // bytes_a            # 16 (bf16) / 8 (fp32)
    cpr = 2 if bytes_a == 4 else 1
    return 6 + cpr * ceil_div(m, 16) * ceil_div(k, kt) * ceil_div(n, 16)


def read_aic(fid):
    """Return the AIC-row pipe busy cycles for kernel function `fid`."""
    p = CSV_DIR / f"{fid}_pipeline_summary.csv"
    with p.open() as f:
        for r in csv.DictReader(f):
            if r["unit"] == "AIC":
                return dict(
                    total=int(r["total_cycles"]),
                    mte2=int(r["mte2_aic_cycles"]),
                    mte1=int(r["mte1_cycles"]),
                    cube=int(r["cube_cycles"]),
                    fixp=int(r["fixp_cycles"]),
                )
    raise RuntimeError(f"no AIC row in {p}")


# RunGemmE2E<float,half,half,float, blockDim, m,k,n, valid..., singleCore..., base..., steps>
# bf16 operands, fp32 accumulate -- the autotiler's default GEMM dtypes.
def emit_split_k_baseline(fid, M, K, N, bm, bk, bn):
    """A reusable no-reuse split-K kernel call (the gemm_performance reference)."""
    return (
        f"void {fid}() {{ RunGemmE2E<float, half, half, float, 1, "
        f"{M}, {K}, {N}, {M}, {K}, {N}, {M}, {K}, {N}, {bm}, {bk}, {bn}, 1, 1, 1, 1>"
        f"(nullptr, nullptr, nullptr); }}"
    )


CMAKE_TEMPLATE = (
    "pto_costmodel_sim_st({name})\n"
    "target_include_directories({name} PRIVATE\n"
    "    ${{PROJECT_SOURCE_DIR}}/" + KERNEL_INCLUDE + "\n"
    ")\n"
    "target_compile_options({name} PRIVATE -D__DAV_C220_CUBE__ -D__DAV_CUBE__ -D__DAV_VEC__)\n"
)

MAIN_HEADER = """// AUTO-GENERATED by l0_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "{kernel_include}"

using namespace pto;
"""


def write_testcase(name, kernel_include, fn_defs, fids, test_suite):
    """Write testcase/<name>/{main.cpp, CMakeLists.txt}."""
    tc = TESTCASE_DIR / name
    tc.mkdir(parents=True, exist_ok=True)
    body = [MAIN_HEADER.format(kernel_include=kernel_include)]
    body += fn_defs
    body.append(f"\nTEST({test_suite}, All) {{")
    body += [f"    LAUNCH_KERNEL({fid}, , (1, nullptr, nullptr));" for fid in fids]
    body.append("}")
    (tc / "main.cpp").write_text("\n".join(body) + "\n")
    (tc / "CMakeLists.txt").write_text(CMAKE_TEMPLATE.format(name=name))
