// AUTO-GENERATED by gm_l1_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "gemm_performance_kernel.cpp"

using namespace pto;

void mc_un_1() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 0.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGemmE2E<float, half, half, float, 1, 2048, 512, 2048, 2048, 512, 2048, 2048, 512, 2048, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void mc_cap_1() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGemmE2E<float, half, half, float, 1, 2048, 512, 2048, 2048, 512, 2048, 2048, 512, 2048, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void mc_un_2() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 0.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGemmE2E<float, half, half, float, 2, 2048, 512, 2048, 2048, 512, 2048, 2048, 512, 1024, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void mc_cap_2() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGemmE2E<float, half, half, float, 2, 2048, 512, 2048, 2048, 512, 2048, 2048, 512, 1024, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void mc_un_4() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 0.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGemmE2E<float, half, half, float, 4, 2048, 512, 2048, 2048, 512, 2048, 2048, 512, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void mc_cap_4() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGemmE2E<float, half, half, float, 4, 2048, 512, 2048, 2048, 512, 2048, 2048, 512, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void mc_un_8() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 0.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGemmE2E<float, half, half, float, 8, 2048, 512, 2048, 2048, 512, 2048, 2048, 512, 256, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void mc_cap_8() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGemmE2E<float, half, half, float, 8, 2048, 512, 2048, 2048, 512, 2048, 2048, 512, 256, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void mc_un_16() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 0.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGemmE2E<float, half, half, float, 16, 2048, 512, 2048, 2048, 512, 2048, 2048, 512, 128, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void mc_cap_16() { auto _m = pto::mocker::evaluator::MakeFlatHillModel(); _m.total_read_gibs = 900.0; pto::mocker::evaluator::SetHillBandwidthModel(_m); RunGemmE2E<float, half, half, float, 16, 2048, 512, 2048, 2048, 512, 2048, 2048, 512, 128, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }

TEST(Gml1Multicore, All) {
    LAUNCH_KERNEL(mc_un_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(mc_cap_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(mc_un_2, , (2, nullptr, nullptr));
    LAUNCH_KERNEL(mc_cap_2, , (2, nullptr, nullptr));
    LAUNCH_KERNEL(mc_un_4, , (4, nullptr, nullptr));
    LAUNCH_KERNEL(mc_cap_4, , (4, nullptr, nullptr));
    LAUNCH_KERNEL(mc_un_8, , (8, nullptr, nullptr));
    LAUNCH_KERNEL(mc_cap_8, , (8, nullptr, nullptr));
    LAUNCH_KERNEL(mc_un_16, , (16, nullptr, nullptr));
    LAUNCH_KERNEL(mc_cap_16, , (16, nullptr, nullptr));
}
