// AUTO-GENERATED by l0_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "asymbuf_kernel.cpp"

using namespace pto;

void as_0_1() { RunGemmFullKAsymBuf<float, half, half, 512, 64, 512, 128, 128, 1>(nullptr, nullptr, nullptr); }
void as_0_2() { RunGemmFullKAsymBuf<float, half, half, 512, 64, 512, 128, 128, 2>(nullptr, nullptr, nullptr); }
void as_1_1() { RunGemmFullKAsymBuf<float, half, half, 512, 64, 512, 256, 128, 1>(nullptr, nullptr, nullptr); }
void as_1_2() { RunGemmFullKAsymBuf<float, half, half, 512, 64, 512, 256, 128, 2>(nullptr, nullptr, nullptr); }
void as_2_1() { RunGemmFullKAsymBuf<float, half, half, 512, 64, 512, 128, 256, 1>(nullptr, nullptr, nullptr); }
void as_2_2() { RunGemmFullKAsymBuf<float, half, half, 512, 64, 512, 128, 256, 2>(nullptr, nullptr, nullptr); }
void as_3_1() { RunGemmFullKAsymBuf<float, half, half, 512, 128, 512, 128, 128, 1>(nullptr, nullptr, nullptr); }
void as_3_2() { RunGemmFullKAsymBuf<float, half, half, 512, 128, 512, 128, 128, 2>(nullptr, nullptr, nullptr); }

TEST(GemmAsymBuf, All) {
    LAUNCH_KERNEL(as_0_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(as_0_2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(as_1_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(as_1_2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(as_2_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(as_2_2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(as_3_1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(as_3_2, , (1, nullptr, nullptr));
}
