// AUTO-GENERATED by vec_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

using namespace pto;


template <int OP, typename T, int ROWS, int COLS, int NOPS>
AICORE inline void VecChain(__gm__ T *src) {
    using ShapeDyn  = pto::Shape<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using StrideDyn = pto::Stride<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using Global    = pto::GlobalTensor<T, ShapeDyn, StrideDyn, pto::Layout::ND>;
    using VT        = pto::Tile<pto::TileType::Vec, T, ROWS, COLS, pto::BLayout::RowMajor, ROWS, COLS>;
    constexpr int nbytes = ROWS * COLS * (int)sizeof(T);
    VT a, b, c;
    TASSIGN(a, 0);
    TASSIGN(b, nbytes);
    TASSIGN(c, 2 * nbytes);
    ShapeDyn  shape(1, 1, 1, ROWS, COLS);
    StrideDyn stride(ROWS * COLS, ROWS * COLS, ROWS * COLS, COLS, 1);
    Global g(src, shape, stride);
    TLOAD(a, g);
    TLOAD(b, g);
    for (int i = 0; i < NOPS; ++i) {
        if constexpr (OP == 0) { TADD(c, a, b); }
        else if constexpr (OP == 1) { TMUL(c, a, b); }
        else if constexpr (OP == 2) { TDIV(c, a, b); }
        else if constexpr (OP == 3) { TEXP(c, a); }
    }
}


// Mirror the ST trowsum/tcolsum tests: full [ROWS,COLS] template (aligned Cols) with
// DYNAMIC valid dims (-1,-1) + runtime ctor giving each tile its real valid shape. No
// TLOAD -- the cost model is data-agnostic, so TASSIGN + the reduce op is enough.
template <typename T, int ROWS, int COLS>
AICORE inline void RowSum() {
    using TD = pto::Tile<pto::TileType::Vec, T, ROWS, COLS, pto::BLayout::RowMajor, -1, -1>;
    constexpr int nbytes = ROWS * COLS * (int)sizeof(T);
    TD src(ROWS, COLS), tmp(ROWS, COLS), dst(ROWS, COLS);
    TASSIGN(src, 0);
    TASSIGN(tmp, nbytes);
    TASSIGN(dst, 2 * nbytes);
    TROWSUM(dst, src, tmp);          // [ROWS,COLS] -> [ROWS,1] (reduce W)
}
template <typename T, int ROWS, int COLS>
AICORE inline void ColSumBin() {
    using TD = pto::Tile<pto::TileType::Vec, T, ROWS, COLS, pto::BLayout::RowMajor, -1, -1>;
    constexpr int nbytes = ROWS * COLS * (int)sizeof(T);
    TD src(ROWS, COLS), tmp((ROWS / 2 > 0 ? ROWS / 2 : 1), COLS), dst(1, COLS);
    TASSIGN(src, 0);
    TASSIGN(tmp, nbytes);
    TASSIGN(dst, 2 * nbytes);
    TCOLSUM(dst, src, tmp, true);    // [ROWS,COLS] -> [1,COLS] (reduce H, binary tree)
}

void fp_add_r1() { VecChain<0, half, 1, 128, 1>(nullptr); }
void fp_add_r2() { VecChain<0, half, 1, 256, 1>(nullptr); }
void fp_add_r4() { VecChain<0, half, 1, 512, 1>(nullptr); }
void fp_add_r8() { VecChain<0, half, 1, 1024, 1>(nullptr); }
void fp_rs_c128() { RowSum<half, 8, 128>(); }
void fp_rs_c256() { RowSum<half, 8, 256>(); }
void fp_rs_c512() { RowSum<half, 8, 512>(); }
void fp_rs_c1024() { RowSum<half, 8, 1024>(); }

TEST(VecFp16, All) {
    LAUNCH_KERNEL(fp_add_r1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fp_add_r2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fp_add_r4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fp_add_r8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fp_rs_c128, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fp_rs_c256, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fp_rs_c512, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(fp_rs_c1024, , (1, nullptr, nullptr));
}
