// AUTO-GENERATED by gm_l1_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "gemm_performance_kernel.cpp"

using namespace pto;

void sp1() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sp2() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sp4() { RunGemmE2E<float, half, half, float, 1, 512, 256, 512, 512, 256, 512, 512, 256, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sp8() { RunGemmE2E<float, half, half, float, 1, 512, 128, 512, 512, 128, 512, 512, 128, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void sp16() { RunGemmE2E<float, half, half, float, 1, 512, 64, 512, 512, 64, 512, 512, 64, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }

TEST(Gml1SplitK, All) {
    LAUNCH_KERNEL(sp1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sp2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sp4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sp8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sp16, , (1, nullptr, nullptr));
}
