// AUTO-GENERATED by vec_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

using namespace pto;


// Online softmax numerator per chunk: rowmax -> center -> exp -> rowsum over [ROWS,CW]. The
// exp runs ONCE per element regardless of NCHUNKS (the wide body splits, it does not repeat).
// The full flash emit adds a thin [H,1] max-merge + running-sum rescale per chunk (a few
// ColMajor/RowMajor reduce-tile ops) -- a small surcharge we account for analytically, omitted
// here to keep one clean RowMajor wide-body kernel. NCHUNKS=1 is the materialized single pass.
template <typename T, int ROWS, int COLS, int NCHUNKS>
AICORE inline void SoftmaxStream() {
    constexpr int CW = COLS / NCHUNKS;                 // chunk width (a multiple of 64)
    using CT = pto::Tile<pto::TileType::Vec, T, ROWS, CW, pto::BLayout::RowMajor, ROWS, CW>;
    using RT = pto::Tile<pto::TileType::Vec, T, ROWS, 1, pto::BLayout::ColMajor, ROWS, 1>;
    constexpr int cb = ROWS * CW * (int)sizeof(T);
    CT xc, tmp; RT mx, sm;
    TASSIGN(xc, 0);
    TASSIGN(tmp, cb);
    TASSIGN(mx, 2 * cb);
    TASSIGN(sm, 2 * cb + ROWS * (int)sizeof(T));
    for (int j = 0; j < NCHUNKS; ++j) {
        TROWMAX(mx, xc, tmp);          // [H,CW] -> [H,1]  chunk max
        TROWEXPANDSUB(xc, xc, mx);     // center (broadcast [H,1] over CW)
        TEXP(xc, xc);                  // exp ONCE over the chunk
        TROWSUM(sm, xc, tmp);          // [H,CW] -> [H,1]  chunk sum
    }
}

void sm_n1() { SoftmaxStream<float, 8, 512, 1>(); }
void sm_n2() { SoftmaxStream<float, 8, 512, 2>(); }
void sm_n4() { SoftmaxStream<float, 8, 512, 4>(); }
void sm_n8() { SoftmaxStream<float, 8, 512, 8>(); }

TEST(VecStream, All) {
    LAUNCH_KERNEL(sm_n1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sm_n2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sm_n4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(sm_n8, , (1, nullptr, nullptr));
}
