// AUTO-GENERATED by gm_l1_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

#include "gemm_performance_kernel.cpp"

using namespace pto;

void dc0() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 16, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc1() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 16, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc2() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 16, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc3() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 16, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc4() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 16, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc5() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc6() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc7() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc8() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc9() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 32, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc10() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc11() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc12() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc13() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc14() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 64, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc15() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc16() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc17() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc18() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc19() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 128, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc20() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 256, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc21() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 256, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc22() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 256, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc23() { RunGemmE2E<float, half, half, float, 1, 512, 512, 512, 512, 512, 512, 512, 512, 512, 256, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc24() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 16, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc25() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 16, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc26() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 16, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc27() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 16, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc28() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 16, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc29() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 32, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc30() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 32, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc31() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 32, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc32() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 32, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc33() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 32, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc34() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 64, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc35() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 64, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc36() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 64, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc37() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 64, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc38() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 64, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc39() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 128, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc40() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 128, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc41() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 128, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc42() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc43() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 128, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc44() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 256, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc45() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 256, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc46() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 256, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc47() { RunGemmE2E<float, half, half, float, 1, 512, 1024, 512, 512, 1024, 512, 512, 1024, 512, 256, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc48() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 16, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc49() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 16, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc50() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 16, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc51() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 16, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc52() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 16, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc53() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 32, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc54() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 32, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc55() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 32, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc56() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 32, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc57() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 32, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc58() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 64, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc59() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 64, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc60() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 64, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc61() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 64, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc62() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 64, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc63() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 128, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc64() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 128, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc65() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 128, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc66() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc67() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 128, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc68() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 256, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc69() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 256, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc70() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 256, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc71() { RunGemmE2E<float, half, half, float, 1, 256, 2048, 256, 256, 2048, 256, 256, 2048, 256, 256, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc72() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 16, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc73() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 16, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc74() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 16, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc75() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 16, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc76() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 16, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc77() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 32, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc78() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 32, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc79() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 32, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc80() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 32, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc81() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 32, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc82() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 64, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc83() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 64, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc84() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 64, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc85() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 64, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc86() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 64, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc87() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 128, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc88() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 128, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc89() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 128, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc90() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 128, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc91() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 128, 64, 256, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc92() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 256, 64, 16, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc93() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 256, 64, 32, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc94() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 256, 64, 64, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }
void dc95() { RunGemmE2E<float, half, half, float, 1, 1024, 128, 1024, 1024, 128, 1024, 1024, 128, 1024, 256, 64, 128, 1, 1, 1, 1>(nullptr, nullptr, nullptr); }

TEST(Gml1Decision, All) {
    LAUNCH_KERNEL(dc0, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc3, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc5, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc6, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc7, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc9, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc10, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc11, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc12, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc13, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc14, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc15, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc16, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc17, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc18, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc19, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc20, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc21, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc22, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc23, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc24, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc25, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc26, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc27, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc28, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc29, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc30, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc31, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc32, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc33, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc34, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc35, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc36, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc37, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc38, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc39, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc40, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc41, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc42, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc43, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc44, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc45, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc46, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc47, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc48, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc49, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc50, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc51, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc52, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc53, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc54, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc55, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc56, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc57, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc58, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc59, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc60, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc61, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc62, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc63, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc64, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc65, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc66, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc67, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc68, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc69, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc70, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc71, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc72, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc73, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc74, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc75, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc76, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc77, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc78, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc79, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc80, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc81, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc82, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc83, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc84, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc85, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc86, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc87, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc88, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc89, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc90, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc91, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc92, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc93, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc94, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dc95, , (1, nullptr, nullptr));
}
