// AUTO-GENERATED by vec_tile_study (run.py). Do not edit by hand.
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <pto/costmodel/perf_sim/launch.hpp>
#include <gtest/gtest.h>

using namespace pto;


// Pipe-sync wrappers (same as gemm_performance_kernel.cpp) -- set_flag/wait_flag are perf-sim
// intrinsics; defined here so the self-contained vec_dma kernel can software-pipeline.
template <pipe_t srcPipe, pipe_t dstPipe>
AICORE inline void SetFlag(uint32_t id) { set_flag(srcPipe, dstPipe, static_cast<event_t>(id)); }
template <pipe_t srcPipe, pipe_t dstPipe>
AICORE inline void WaitFlag(uint32_t id) { wait_flag(srcPipe, dstPipe, static_cast<event_t>(id)); }
template <typename T, int H, int W, int NLD>
AICORE inline void DmaLoad(__gm__ T *src) {
    using ShapeDyn  = pto::Shape<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using StrideDyn = pto::Stride<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using Global    = pto::GlobalTensor<T, ShapeDyn, StrideDyn, pto::Layout::ND>;
    using VT = pto::Tile<pto::TileType::Vec, T, H, W, pto::BLayout::RowMajor, H, W>;
    VT tile;
    TASSIGN(tile, 0);
    ShapeDyn  shape(1, 1, 1, H, W);
    StrideDyn stride(H * W, H * W, H * W, W, 1);
    for (int i = 0; i < NLD; ++i) { Global g(src, shape, stride); TLOAD(tile, g); }
}
template <typename T, int H, int W, int NT>
AICORE inline void LoadComputeStore(__gm__ T *buf) {
    using ShapeDyn  = pto::Shape<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using StrideDyn = pto::Stride<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using Global    = pto::GlobalTensor<T, ShapeDyn, StrideDyn, pto::Layout::ND>;
    using VT = pto::Tile<pto::TileType::Vec, T, H, W, pto::BLayout::RowMajor, H, W>;
    constexpr int nb = H * W * (int)sizeof(T);
    VT a, b;
    TASSIGN(a, 0);
    TASSIGN(b, nb);
    ShapeDyn  shape(1, 1, 1, H, W);
    StrideDyn stride(H * W, H * W, H * W, W, 1);
    for (int i = 0; i < NT; ++i) {
        Global g(buf, shape, stride);
        TLOAD(a, g);          // GM->UB (mte2)
        TADD(b, a, a);        // VEC compute
        TMUL(b, b, a);
        TSTORE(g, b);         // UB->GM (mte3)
    }
}
// Software-pipelined: PREFETCH tile s+1 (MTE2) before computing tile s (VEC), with per-buffer
// flags so the next load overlaps this compute (a0/b0 vs a1/b1 ping-pong). This is what the
// emit must do to hit the max(compute,ddr) roofline -- buffer alternation ALONE doesn't overlap
// (the perf-sim sums program-order ops); the SetFlag/WaitFlag pipeline is what creates it.
template <typename T, int H, int W, int NT>
AICORE inline void Pipelined(__gm__ T *buf) {
    using ShapeDyn  = pto::Shape<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using StrideDyn = pto::Stride<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using Global    = pto::GlobalTensor<T, ShapeDyn, StrideDyn, pto::Layout::ND>;
    using VT = pto::Tile<pto::TileType::Vec, T, H, W, pto::BLayout::RowMajor, H, W>;
    constexpr int nb = H * W * (int)sizeof(T);
    VT a0, a1, b0, b1;
    TASSIGN(a0, 0); TASSIGN(a1, nb); TASSIGN(b0, 2 * nb); TASSIGN(b1, 3 * nb);
    ShapeDyn  shape(1, 1, 1, H, W);
    StrideDyn stride(H * W, H * W, H * W, W, 1);
    Global g0(buf, shape, stride);
    TLOAD(a0, g0);                                   // prefetch tile 0
    SetFlag<PIPE_MTE2, PIPE_V>(0);
    for (int s = 0; s < NT; ++s) {
        if (s + 1 < NT) {                            // prefetch tile s+1 -> overlaps this compute
            Global gn(buf, shape, stride);
            if ((s + 1) & 1) { TLOAD(a1, gn); SetFlag<PIPE_MTE2, PIPE_V>(1); }
            else             { TLOAD(a0, gn); SetFlag<PIPE_MTE2, PIPE_V>(0); }
        }
        Global gs(buf, shape, stride);
        if (s & 1) { WaitFlag<PIPE_MTE2, PIPE_V>(1); TADD(b1, a1, a1); TMUL(b1, b1, a1); TSTORE(gs, b1); }
        else       { WaitFlag<PIPE_MTE2, PIPE_V>(0); TADD(b0, a0, a0); TMUL(b0, b0, a0); TSTORE(gs, b0); }
    }
}

void dma_w16() { DmaLoad<float, 256, 16, 32>(nullptr); }
void dma_w32() { DmaLoad<float, 128, 32, 32>(nullptr); }
void dma_w64() { DmaLoad<float, 64, 64, 32>(nullptr); }
void dma_w128() { DmaLoad<float, 32, 128, 32>(nullptr); }
void dma_w256() { DmaLoad<float, 16, 256, 32>(nullptr); }
void dma_w512() { DmaLoad<float, 8, 512, 32>(nullptr); }
void rf_n1() { LoadComputeStore<float, 64, 256, 1>(nullptr); }
void rf_n2() { LoadComputeStore<float, 64, 256, 2>(nullptr); }
void rf_n4() { LoadComputeStore<float, 64, 256, 4>(nullptr); }
void rf_n8() { LoadComputeStore<float, 64, 256, 8>(nullptr); }
void db_n2() { Pipelined<float, 64, 128, 2>(nullptr); }
void db_n4() { Pipelined<float, 64, 128, 4>(nullptr); }
void db_n8() { Pipelined<float, 64, 128, 8>(nullptr); }

TEST(VecDma, All) {
    LAUNCH_KERNEL(dma_w16, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dma_w32, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dma_w64, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dma_w128, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dma_w256, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(dma_w512, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rf_n1, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rf_n2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rf_n4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(rf_n8, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(db_n2, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(db_n4, , (1, nullptr, nullptr));
    LAUNCH_KERNEL(db_n8, , (1, nullptr, nullptr));
}
